SELECT 'users' AS table_name, COUNT(*) AS row_count FROM users
UNION ALL SELECT 'roles', COUNT(*) FROM roles
UNION ALL SELECT 'permissions', COUNT(*) FROM permissions
UNION ALL SELECT 'user_roles', COUNT(*) FROM user_roles
UNION ALL SELECT 'role_permissions', COUNT(*) FROM role_permissions
UNION ALL SELECT 'stores', COUNT(*) FROM stores
UNION ALL SELECT 'store_details', COUNT(*) FROM store_details
UNION ALL SELECT 'addresses', COUNT(*) FROM addresses
UNION ALL SELECT 'shipping_settings', COUNT(*) FROM shipping_settings
UNION ALL SELECT 'catalog_groups', COUNT(*) FROM catalog_groups
UNION ALL SELECT 'categories', COUNT(*) FROM categories
UNION ALL SELECT 'product_attributes', COUNT(*) FROM product_attributes
UNION ALL SELECT 'products', COUNT(*) FROM products
UNION ALL SELECT 'product_categories', COUNT(*) FROM product_categories
UNION ALL SELECT 'product_attribute_values', COUNT(*) FROM product_attribute_values
UNION ALL SELECT 'product_variants', COUNT(*) FROM product_variants
UNION ALL SELECT 'product_variant_values', COUNT(*) FROM product_variant_values
UNION ALL SELECT 'product_images', COUNT(*) FROM product_images
UNION ALL SELECT 'banners', COUNT(*) FROM banners
UNION ALL SELECT 'promotions', COUNT(*) FROM promotions
UNION ALL SELECT 'vouchers', COUNT(*) FROM vouchers
UNION ALL SELECT 'carts', COUNT(*) FROM carts
UNION ALL SELECT 'cart_items', COUNT(*) FROM cart_items
UNION ALL SELECT 'wishlists', COUNT(*) FROM wishlists
UNION ALL SELECT 'wishlist_items', COUNT(*) FROM wishlist_items
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'sub_orders', COUNT(*) FROM sub_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM order_items
UNION ALL SELECT 'payments', COUNT(*) FROM payments
UNION ALL SELECT 'promotion_payments', COUNT(*) FROM promotion_payments
UNION ALL SELECT 'financial_transactions', COUNT(*) FROM financial_transactions
UNION ALL SELECT 'financial_payment_histories', COUNT(*) FROM financial_payment_histories
UNION ALL SELECT 'stock_movements', COUNT(*) FROM stock_movements
UNION ALL SELECT 'raw_materials', COUNT(*) FROM raw_materials
UNION ALL SELECT 'raw_material_stock_movements', COUNT(*) FROM raw_material_stock_movements
UNION ALL SELECT 'product_costings', COUNT(*) FROM product_costings
UNION ALL SELECT 'product_materials', COUNT(*) FROM product_materials
UNION ALL SELECT 'showcases', COUNT(*) FROM showcases
UNION ALL SELECT 'showcase_products', COUNT(*) FROM showcase_products
UNION ALL SELECT 'support_tickets', COUNT(*) FROM support_tickets
UNION ALL SELECT 'support_ticket_messages', COUNT(*) FROM support_ticket_messages
UNION ALL SELECT 'missions', COUNT(*) FROM missions
UNION ALL SELECT 'user_vouchers', COUNT(*) FROM user_vouchers
UNION ALL SELECT 'mission_user_progress', COUNT(*) FROM mission_user_progress
UNION ALL SELECT 'product_reviews', COUNT(*) FROM product_reviews
UNION ALL SELECT 'conversations', COUNT(*) FROM conversations
UNION ALL SELECT 'conversation_participants', COUNT(*) FROM conversation_participants
UNION ALL SELECT 'chat_messages', COUNT(*) FROM chat_messages
UNION ALL SELECT 'chat_message_reads', COUNT(*) FROM chat_message_reads
UNION ALL SELECT 'admin_notifications', COUNT(*) FROM admin_notifications
ORDER BY table_name;
